/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "/input/MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#include "etsi_its_mcm_thi_prima_coding/asn_McmCategory.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_asn_McmCategory_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  11 }	/* (0..11) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_asn_McmCategory_value2enum_1[] = {
	{ 0,	7,	"request" },
	{ 1,	6,	"accept" },
	{ 2,	6,	"reject" },
	{ 3,	5,	"offer" },
	{ 4,	7,	"confirm" },
	{ 5,	7,	"execute" },
	{ 6,	6,	"cancel" },
	{ 7,	5,	"abort" },
	{ 8,	16,	"cascadingRequest" },
	{ 9,	15,	"cascadingAccept" },
	{ 10,	15,	"cascadingReject" },
	{ 11,	16,	"cascadingExecute" }
};
static const unsigned int asn_MAP_asn_McmCategory_enum2value_1[] = {
	7,	/* abort(7) */
	1,	/* accept(1) */
	6,	/* cancel(6) */
	9,	/* cascadingAccept(9) */
	11,	/* cascadingExecute(11) */
	10,	/* cascadingReject(10) */
	8,	/* cascadingRequest(8) */
	4,	/* confirm(4) */
	5,	/* execute(5) */
	3,	/* offer(3) */
	2,	/* reject(2) */
	0	/* request(0) */
};
const asn_INTEGER_specifics_t asn_SPC_asn_McmCategory_specs_1 = {
	asn_MAP_asn_McmCategory_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_asn_McmCategory_enum2value_1,	/* N => "tag"; sorted by N */
	12,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_asn_McmCategory_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_asn_McmCategory = {
	"McmCategory",
	"McmCategory",
	&asn_OP_NativeEnumerated,
	asn_DEF_asn_McmCategory_tags_1,
	sizeof(asn_DEF_asn_McmCategory_tags_1)
		/sizeof(asn_DEF_asn_McmCategory_tags_1[0]), /* 1 */
	asn_DEF_asn_McmCategory_tags_1,	/* Same as above */
	sizeof(asn_DEF_asn_McmCategory_tags_1)
		/sizeof(asn_DEF_asn_McmCategory_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_asn_McmCategory_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_asn_McmCategory_specs_1	/* Additional specs */
};

