/** ============================================================================
MIT License

Copyright (c) 2023-2025 Institute for Automotive Engineering (ika), RWTH Aachen University

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
============================================================================= */

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  asn1ToConversionHeader.py \
  -t \
  asn \
  /home/lobo/Development/etsi_its_message/ros2_ws/src/etsi_its_messages/asn1/raw/mcm_thi_prima/cdd/ITS-Container.asn \
  /home/lobo/Development/etsi_its_message/ros2_ws/src/etsi_its_messages/asn1/raw/cam_en302637_2/CAM-PDU-Descriptions.asn \
  /home/lobo/Development/etsi_its_message/ros2_ws/src/etsi_its_messages/asn1/raw/mcm_thi_prima/MCM-PDU-Descriptions.asn \
  -o \
  /home/lobo/mcm_conversion/
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
ManeuverNegotiationContainer ::= SEQUENCE {
    mcmCategory McmCategory,
    priorityManeuver PriorityManeuver,
    cooperationTypeMCM CooperationTypeMCM,
    requestID RequestID,
    requestedTrajectory TrajectoryMCM,
    offeredTrajectory TrajectoryMCM,
    alternativeTrajectory TrajectoryMCM OPTIONAL,
    reasonRequest Reason OPTIONAL,
    reasonReject ReasonReject OPTIONAL,
    -- laneID LaneID OPTIONAL,
    -- laneIDTrajEnd LaneID OPTIONAL,
    cooperationCostTrajectory CooperationCostTrajectory OPTIONAL,
    numberOfVehicles NumberOfVehicles,
    negotiationVehicleID1 StationID,
    negotiationVehicleID2 StationID OPTIONAL
}
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_asn_coding/asn_ManeuverNegotiationContainer.h>
#include <etsi_its_asn_conversion/convertCooperationCostTrajectory.h>
#include <etsi_its_asn_conversion/convertCooperationTypeMCM.h>
#include <etsi_its_asn_conversion/convertMcmCategory.h>
#include <etsi_its_asn_conversion/convertNumberOfVehicles.h>
#include <etsi_its_asn_conversion/convertPriorityManeuver.h>
#include <etsi_its_asn_conversion/convertReason.h>
#include <etsi_its_asn_conversion/convertReasonReject.h>
#include <etsi_its_asn_conversion/convertRequestID.h>
#include <etsi_its_asn_conversion/convertStationID.h>
#include <etsi_its_asn_conversion/convertTrajectoryMCM.h>
#ifdef ROS1
#include <etsi_its_asn_msgs/ManeuverNegotiationContainer.h>
namespace asn_msgs = etsi_its_asn_msgs;
#else
#include <etsi_its_asn_msgs/msg/maneuver_negotiation_container.hpp>
namespace asn_msgs = etsi_its_asn_msgs::msg;
#endif


namespace etsi_its_asn_conversion {

void toRos_ManeuverNegotiationContainer(const asn_ManeuverNegotiationContainer_t& in, asn_msgs::ManeuverNegotiationContainer& out) {
  toRos_McmCategory(in.mcmCategory, out.mcm_category);
  toRos_PriorityManeuver(in.priorityManeuver, out.priority_maneuver);
  toRos_CooperationTypeMCM(in.cooperationTypeMCM, out.cooperation_type_mcm);
  toRos_RequestID(in.requestID, out.request_id);
  toRos_TrajectoryMCM(in.requestedTrajectory, out.requested_trajectory);
  toRos_TrajectoryMCM(in.offeredTrajectory, out.offered_trajectory);
  if (in.alternativeTrajectory) {
    toRos_TrajectoryMCM(*in.alternativeTrajectory, out.alternative_trajectory);
    out.alternative_trajectory_is_present = true;
  }
  if (in.reasonRequest) {
    toRos_Reason(*in.reasonRequest, out.reason_request);
    out.reason_request_is_present = true;
  }
  if (in.reasonReject) {
    toRos_ReasonReject(*in.reasonReject, out.reason_reject);
    out.reason_reject_is_present = true;
  }
  if (in.cooperationCostTrajectory) {
    toRos_CooperationCostTrajectory(*in.cooperationCostTrajectory, out.cooperation_cost_trajectory);
    out.cooperation_cost_trajectory_is_present = true;
  }
  toRos_NumberOfVehicles(in.numberOfVehicles, out.number_of_vehicles);
  toRos_StationID(in.negotiationVehicleID1, out.negotiation_vehicle_id1);
  if (in.negotiationVehicleID2) {
    toRos_StationID(*in.negotiationVehicleID2, out.negotiation_vehicle_id2);
    out.negotiation_vehicle_id2_is_present = true;
  }
}

void toStruct_ManeuverNegotiationContainer(const asn_msgs::ManeuverNegotiationContainer& in, asn_ManeuverNegotiationContainer_t& out) {
  memset(&out, 0, sizeof(asn_ManeuverNegotiationContainer_t));
  toStruct_McmCategory(in.mcm_category, out.mcmCategory);
  toStruct_PriorityManeuver(in.priority_maneuver, out.priorityManeuver);
  toStruct_CooperationTypeMCM(in.cooperation_type_mcm, out.cooperationTypeMCM);
  toStruct_RequestID(in.request_id, out.requestID);
  toStruct_TrajectoryMCM(in.requested_trajectory, out.requestedTrajectory);
  toStruct_TrajectoryMCM(in.offered_trajectory, out.offeredTrajectory);
  if (in.alternative_trajectory_is_present) {
    out.alternativeTrajectory = (asn_TrajectoryMCM_t*) calloc(1, sizeof(asn_TrajectoryMCM_t));
    toStruct_TrajectoryMCM(in.alternative_trajectory, *out.alternativeTrajectory);
  }
  if (in.reason_request_is_present) {
    out.reasonRequest = (asn_Reason_t*) calloc(1, sizeof(asn_Reason_t));
    toStruct_Reason(in.reason_request, *out.reasonRequest);
  }
  if (in.reason_reject_is_present) {
    out.reasonReject = (asn_ReasonReject_t*) calloc(1, sizeof(asn_ReasonReject_t));
    toStruct_ReasonReject(in.reason_reject, *out.reasonReject);
  }
  if (in.cooperation_cost_trajectory_is_present) {
    out.cooperationCostTrajectory = (asn_CooperationCostTrajectory_t*) calloc(1, sizeof(asn_CooperationCostTrajectory_t));
    toStruct_CooperationCostTrajectory(in.cooperation_cost_trajectory, *out.cooperationCostTrajectory);
  }
  toStruct_NumberOfVehicles(in.number_of_vehicles, out.numberOfVehicles);
  toStruct_StationID(in.negotiation_vehicle_id1, out.negotiationVehicleID1);
  if (in.negotiation_vehicle_id2_is_present) {
    out.negotiationVehicleID2 = (asn_StationID_t*) calloc(1, sizeof(asn_StationID_t));
    toStruct_StationID(in.negotiation_vehicle_id2, *out.negotiationVehicleID2);
  }
}

}
