/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_DangerousGoodsExtended_H_
#define	_asn_DangerousGoodsExtended_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_thi_prima_coding/asn_DangerousGoodsBasic.h"
#include <etsi_its_mcm_thi_prima_coding/NativeInteger.h>
#include <etsi_its_mcm_thi_prima_coding/BOOLEAN.h>
#include <etsi_its_mcm_thi_prima_coding/IA5String.h>
#include "etsi_its_mcm_thi_prima_coding/asn_PhoneNumber.h"
#include <etsi_its_mcm_thi_prima_coding/UTF8String.h>
#include <etsi_its_mcm_thi_prima_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asn_DangerousGoodsExtended */
typedef struct asn_DangerousGoodsExtended {
	asn_DangerousGoodsBasic_t	 dangerousGoodsType;
	long	 unNumber;
	BOOLEAN_t	 elevatedTemperature;
	BOOLEAN_t	 tunnelsRestricted;
	BOOLEAN_t	 limitedQuantity;
	IA5String_t	*emergencyActionCode;	/* OPTIONAL */
	asn_PhoneNumber_t	*phoneNumber;	/* OPTIONAL */
	UTF8String_t	*companyName;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asn_DangerousGoodsExtended_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_DangerousGoodsExtended;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_DangerousGoodsExtended_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
