/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_AdverseWeatherCondition_VisibilitySubCauseCode_H_
#define	_asn_AdverseWeatherCondition_VisibilitySubCauseCode_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_AdverseWeatherCondition_VisibilitySubCauseCode {
	asn_AdverseWeatherCondition_VisibilitySubCauseCode_unavailable	= 0,
	asn_AdverseWeatherCondition_VisibilitySubCauseCode_fog	= 1,
	asn_AdverseWeatherCondition_VisibilitySubCauseCode_smoke	= 2,
	asn_AdverseWeatherCondition_VisibilitySubCauseCode_heavySnowfall	= 3,
	asn_AdverseWeatherCondition_VisibilitySubCauseCode_heavyRain	= 4,
	asn_AdverseWeatherCondition_VisibilitySubCauseCode_heavyHail	= 5,
	asn_AdverseWeatherCondition_VisibilitySubCauseCode_lowSunGlare	= 6,
	asn_AdverseWeatherCondition_VisibilitySubCauseCode_sandstorms	= 7,
	asn_AdverseWeatherCondition_VisibilitySubCauseCode_swarmsOfInsects	= 8
} e_asn_AdverseWeatherCondition_VisibilitySubCauseCode;

/* asn_AdverseWeatherCondition-VisibilitySubCauseCode */
typedef long	 asn_AdverseWeatherCondition_VisibilitySubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_AdverseWeatherCondition_VisibilitySubCauseCode;
asn_struct_free_f asn_AdverseWeatherCondition_VisibilitySubCauseCode_free;
asn_struct_print_f asn_AdverseWeatherCondition_VisibilitySubCauseCode_print;
asn_constr_check_f asn_AdverseWeatherCondition_VisibilitySubCauseCode_constraint;
per_type_decoder_f asn_AdverseWeatherCondition_VisibilitySubCauseCode_decode_uper;
per_type_encoder_f asn_AdverseWeatherCondition_VisibilitySubCauseCode_encode_uper;
per_type_decoder_f asn_AdverseWeatherCondition_VisibilitySubCauseCode_decode_aper;
per_type_encoder_f asn_AdverseWeatherCondition_VisibilitySubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_AdverseWeatherCondition_VisibilitySubCauseCode_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
