/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_WrongWayDrivingSubCauseCode_H_
#define	_asn_WrongWayDrivingSubCauseCode_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_WrongWayDrivingSubCauseCode {
	asn_WrongWayDrivingSubCauseCode_unavailable	= 0,
	asn_WrongWayDrivingSubCauseCode_wrongLane	= 1,
	asn_WrongWayDrivingSubCauseCode_wrongDirection	= 2
} e_asn_WrongWayDrivingSubCauseCode;

/* asn_WrongWayDrivingSubCauseCode */
typedef long	 asn_WrongWayDrivingSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_WrongWayDrivingSubCauseCode;
asn_struct_free_f asn_WrongWayDrivingSubCauseCode_free;
asn_struct_print_f asn_WrongWayDrivingSubCauseCode_print;
asn_constr_check_f asn_WrongWayDrivingSubCauseCode_constraint;
per_type_decoder_f asn_WrongWayDrivingSubCauseCode_decode_uper;
per_type_encoder_f asn_WrongWayDrivingSubCauseCode_encode_uper;
per_type_decoder_f asn_WrongWayDrivingSubCauseCode_decode_aper;
per_type_encoder_f asn_WrongWayDrivingSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_WrongWayDrivingSubCauseCode_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
