/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_AccidentSubCauseCode_H_
#define	_asn_AccidentSubCauseCode_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_AccidentSubCauseCode {
	asn_AccidentSubCauseCode_unavailable	= 0,
	asn_AccidentSubCauseCode_multiVehicleAccident	= 1,
	asn_AccidentSubCauseCode_heavyAccident	= 2,
	asn_AccidentSubCauseCode_accidentInvolvingLorry	= 3,
	asn_AccidentSubCauseCode_accidentInvolvingBus	= 4,
	asn_AccidentSubCauseCode_accidentInvolvingHazardousMaterials	= 5,
	asn_AccidentSubCauseCode_accidentOnOppositeLane	= 6,
	asn_AccidentSubCauseCode_unsecuredAccident	= 7,
	asn_AccidentSubCauseCode_assistanceRequested	= 8
} e_asn_AccidentSubCauseCode;

/* asn_AccidentSubCauseCode */
typedef long	 asn_AccidentSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_AccidentSubCauseCode;
asn_struct_free_f asn_AccidentSubCauseCode_free;
asn_struct_print_f asn_AccidentSubCauseCode_print;
asn_constr_check_f asn_AccidentSubCauseCode_constraint;
per_type_decoder_f asn_AccidentSubCauseCode_decode_uper;
per_type_encoder_f asn_AccidentSubCauseCode_encode_uper;
per_type_decoder_f asn_AccidentSubCauseCode_decode_aper;
per_type_encoder_f asn_AccidentSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_AccidentSubCauseCode_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
