/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_TurningRadius_H_
#define	_asn_TurningRadius_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_TurningRadius {
	asn_TurningRadius_point4Meters	= 1,
	asn_TurningRadius_unavailable	= 255
} e_asn_TurningRadius;

/* asn_TurningRadius */
typedef long	 asn_TurningRadius_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_TurningRadius;
asn_struct_free_f asn_TurningRadius_free;
asn_struct_print_f asn_TurningRadius_print;
asn_constr_check_f asn_TurningRadius_constraint;
per_type_decoder_f asn_TurningRadius_decode_uper;
per_type_encoder_f asn_TurningRadius_encode_uper;
per_type_decoder_f asn_TurningRadius_decode_aper;
per_type_encoder_f asn_TurningRadius_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_TurningRadius_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
