/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "/input/CAM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_SpecialVehicleContainer_H_
#define	_asn_SpecialVehicleContainer_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_thi_prima_coding/asn_PublicTransportContainer.h"
#include "etsi_its_mcm_thi_prima_coding/asn_SpecialTransportContainer.h"
#include "etsi_its_mcm_thi_prima_coding/asn_DangerousGoodsContainer.h"
#include "etsi_its_mcm_thi_prima_coding/asn_RoadWorksContainerBasic.h"
#include "etsi_its_mcm_thi_prima_coding/asn_RescueContainer.h"
#include "etsi_its_mcm_thi_prima_coding/asn_EmergencyContainer.h"
#include "etsi_its_mcm_thi_prima_coding/asn_SafetyCarContainer.h"
#include <etsi_its_mcm_thi_prima_coding/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_SpecialVehicleContainer_PR {
	asn_SpecialVehicleContainer_PR_NOTHING,	/* No components present */
	asn_SpecialVehicleContainer_PR_publicTransportContainer,
	asn_SpecialVehicleContainer_PR_specialTransportContainer,
	asn_SpecialVehicleContainer_PR_dangerousGoodsContainer,
	asn_SpecialVehicleContainer_PR_roadWorksContainerBasic,
	asn_SpecialVehicleContainer_PR_rescueContainer,
	asn_SpecialVehicleContainer_PR_emergencyContainer,
	asn_SpecialVehicleContainer_PR_safetyCarContainer
	/* Extensions may appear below */
	
} asn_SpecialVehicleContainer_PR;

/* asn_SpecialVehicleContainer */
typedef struct asn_SpecialVehicleContainer {
	asn_SpecialVehicleContainer_PR present;
	union asn_SpecialVehicleContainer_u {
		asn_PublicTransportContainer_t	 publicTransportContainer;
		asn_SpecialTransportContainer_t	 specialTransportContainer;
		asn_DangerousGoodsContainer_t	 dangerousGoodsContainer;
		asn_RoadWorksContainerBasic_t	 roadWorksContainerBasic;
		asn_RescueContainer_t	 rescueContainer;
		asn_EmergencyContainer_t	 emergencyContainer;
		asn_SafetyCarContainer_t	 safetyCarContainer;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asn_SpecialVehicleContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_SpecialVehicleContainer;
extern asn_CHOICE_specifics_t asn_SPC_asn_SpecialVehicleContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_asn_SpecialVehicleContainer_1[7];
extern asn_per_constraints_t asn_PER_type_asn_SpecialVehicleContainer_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_SpecialVehicleContainer_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
