/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_ExteriorLights_H_
#define	_asn_ExteriorLights_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_ExteriorLights {
	asn_ExteriorLights_lowBeamHeadlightsOn	= 0,
	asn_ExteriorLights_highBeamHeadlightsOn	= 1,
	asn_ExteriorLights_leftTurnSignalOn	= 2,
	asn_ExteriorLights_rightTurnSignalOn	= 3,
	asn_ExteriorLights_daytimeRunningLightsOn	= 4,
	asn_ExteriorLights_reverseLightOn	= 5,
	asn_ExteriorLights_fogLightOn	= 6,
	asn_ExteriorLights_parkingLightsOn	= 7
} e_asn_ExteriorLights;

/* asn_ExteriorLights */
typedef BIT_STRING_t	 asn_ExteriorLights_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_asn_ExteriorLights_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_asn_ExteriorLights;
asn_struct_free_f asn_ExteriorLights_free;
asn_struct_print_f asn_ExteriorLights_print;
asn_constr_check_f asn_ExteriorLights_constraint;
per_type_decoder_f asn_ExteriorLights_decode_uper;
per_type_encoder_f asn_ExteriorLights_encode_uper;
per_type_decoder_f asn_ExteriorLights_decode_aper;
per_type_encoder_f asn_ExteriorLights_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_ExteriorLights_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
