/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_EnergyStorageType_H_
#define	_asn_EnergyStorageType_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_EnergyStorageType {
	asn_EnergyStorageType_hydrogenStorage	= 0,
	asn_EnergyStorageType_electricEnergyStorage	= 1,
	asn_EnergyStorageType_liquidPropaneGas	= 2,
	asn_EnergyStorageType_compressedNaturalGas	= 3,
	asn_EnergyStorageType_diesel	= 4,
	asn_EnergyStorageType_gasoline	= 5,
	asn_EnergyStorageType_ammonia	= 6
} e_asn_EnergyStorageType;

/* asn_EnergyStorageType */
typedef BIT_STRING_t	 asn_EnergyStorageType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_EnergyStorageType;
asn_struct_free_f asn_EnergyStorageType_free;
asn_struct_print_f asn_EnergyStorageType_print;
asn_constr_check_f asn_EnergyStorageType_constraint;
per_type_decoder_f asn_EnergyStorageType_decode_uper;
per_type_encoder_f asn_EnergyStorageType_encode_uper;
per_type_decoder_f asn_EnergyStorageType_decode_aper;
per_type_encoder_f asn_EnergyStorageType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_EnergyStorageType_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
