/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_AltitudeConfidence_H_
#define	_asn_AltitudeConfidence_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_AltitudeConfidence {
	asn_AltitudeConfidence_alt_000_01	= 0,
	asn_AltitudeConfidence_alt_000_02	= 1,
	asn_AltitudeConfidence_alt_000_05	= 2,
	asn_AltitudeConfidence_alt_000_10	= 3,
	asn_AltitudeConfidence_alt_000_20	= 4,
	asn_AltitudeConfidence_alt_000_50	= 5,
	asn_AltitudeConfidence_alt_001_00	= 6,
	asn_AltitudeConfidence_alt_002_00	= 7,
	asn_AltitudeConfidence_alt_005_00	= 8,
	asn_AltitudeConfidence_alt_010_00	= 9,
	asn_AltitudeConfidence_alt_020_00	= 10,
	asn_AltitudeConfidence_alt_050_00	= 11,
	asn_AltitudeConfidence_alt_100_00	= 12,
	asn_AltitudeConfidence_alt_200_00	= 13,
	asn_AltitudeConfidence_outOfRange	= 14,
	asn_AltitudeConfidence_unavailable	= 15
} e_asn_AltitudeConfidence;

/* asn_AltitudeConfidence */
typedef long	 asn_AltitudeConfidence_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_asn_AltitudeConfidence_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_asn_AltitudeConfidence;
extern const asn_INTEGER_specifics_t asn_SPC_asn_AltitudeConfidence_specs_1;
asn_struct_free_f asn_AltitudeConfidence_free;
asn_struct_print_f asn_AltitudeConfidence_print;
asn_constr_check_f asn_AltitudeConfidence_constraint;
per_type_decoder_f asn_AltitudeConfidence_decode_uper;
per_type_encoder_f asn_AltitudeConfidence_encode_uper;
per_type_decoder_f asn_AltitudeConfidence_decode_aper;
per_type_encoder_f asn_AltitudeConfidence_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_AltitudeConfidence_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
