/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_CenDsrcTollingZone_H_
#define	_asn_CenDsrcTollingZone_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_thi_prima_coding/asn_Latitude.h"
#include "etsi_its_mcm_thi_prima_coding/asn_Longitude.h"
#include "etsi_its_mcm_thi_prima_coding/asn_CenDsrcTollingZoneID.h"
#include <etsi_its_mcm_thi_prima_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asn_CenDsrcTollingZone */
typedef struct asn_CenDsrcTollingZone {
	asn_Latitude_t	 protectedZoneLatitude;
	asn_Longitude_t	 protectedZoneLongitude;
	asn_CenDsrcTollingZoneID_t	*cenDsrcTollingZoneID;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asn_CenDsrcTollingZone_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_CenDsrcTollingZone;
extern asn_SEQUENCE_specifics_t asn_SPC_asn_CenDsrcTollingZone_specs_1;
extern asn_TYPE_member_t asn_MBR_asn_CenDsrcTollingZone_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _asn_CenDsrcTollingZone_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
