/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "/input/CAM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_BasicVehicleContainerHighFrequency_H_
#define	_asn_BasicVehicleContainerHighFrequency_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_thi_prima_coding/asn_Heading.h"
#include "etsi_its_mcm_thi_prima_coding/asn_Speed.h"
#include "etsi_its_mcm_thi_prima_coding/asn_DriveDirection.h"
#include "etsi_its_mcm_thi_prima_coding/asn_VehicleLength.h"
#include "etsi_its_mcm_thi_prima_coding/asn_VehicleWidth.h"
#include "etsi_its_mcm_thi_prima_coding/asn_LongitudinalAcceleration.h"
#include "etsi_its_mcm_thi_prima_coding/asn_Curvature.h"
#include "etsi_its_mcm_thi_prima_coding/asn_CurvatureCalculationMode.h"
#include "etsi_its_mcm_thi_prima_coding/asn_YawRate.h"
#include "etsi_its_mcm_thi_prima_coding/asn_AccelerationControl.h"
#include "etsi_its_mcm_thi_prima_coding/asn_LanePosition.h"
#include "etsi_its_mcm_thi_prima_coding/asn_PerformanceClass.h"
#include <etsi_its_mcm_thi_prima_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct asn_SteeringWheelAngle;
struct asn_LateralAcceleration;
struct asn_VerticalAcceleration;
struct asn_CenDsrcTollingZone;

/* asn_BasicVehicleContainerHighFrequency */
typedef struct asn_BasicVehicleContainerHighFrequency {
	asn_Heading_t	 heading;
	asn_Speed_t	 speed;
	asn_DriveDirection_t	 driveDirection;
	asn_VehicleLength_t	 vehicleLength;
	asn_VehicleWidth_t	 vehicleWidth;
	asn_LongitudinalAcceleration_t	 longitudinalAcceleration;
	asn_Curvature_t	 curvature;
	asn_CurvatureCalculationMode_t	 curvatureCalculationMode;
	asn_YawRate_t	 yawRate;
	asn_AccelerationControl_t	*accelerationControl;	/* OPTIONAL */
	asn_LanePosition_t	*lanePosition;	/* OPTIONAL */
	struct asn_SteeringWheelAngle	*steeringWheelAngle;	/* OPTIONAL */
	struct asn_LateralAcceleration	*lateralAcceleration;	/* OPTIONAL */
	struct asn_VerticalAcceleration	*verticalAcceleration;	/* OPTIONAL */
	asn_PerformanceClass_t	*performanceClass;	/* OPTIONAL */
	struct asn_CenDsrcTollingZone	*cenDsrcTollingZone;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asn_BasicVehicleContainerHighFrequency_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_BasicVehicleContainerHighFrequency;
extern asn_SEQUENCE_specifics_t asn_SPC_asn_BasicVehicleContainerHighFrequency_specs_1;
extern asn_TYPE_member_t asn_MBR_asn_BasicVehicleContainerHighFrequency_1[16];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_mcm_thi_prima_coding/asn_SteeringWheelAngle.h"
#include "etsi_its_mcm_thi_prima_coding/asn_LateralAcceleration.h"
#include "etsi_its_mcm_thi_prima_coding/asn_VerticalAcceleration.h"
#include "etsi_its_mcm_thi_prima_coding/asn_CenDsrcTollingZone.h"

#endif	/* _asn_BasicVehicleContainerHighFrequency_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
