/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_RelevanceDistance_H_
#define	_asn_RelevanceDistance_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_RelevanceDistance {
	asn_RelevanceDistance_lessThan50m	= 0,
	asn_RelevanceDistance_lessThan100m	= 1,
	asn_RelevanceDistance_lessThan200m	= 2,
	asn_RelevanceDistance_lessThan500m	= 3,
	asn_RelevanceDistance_lessThan1000m	= 4,
	asn_RelevanceDistance_lessThan5km	= 5,
	asn_RelevanceDistance_lessThan10km	= 6,
	asn_RelevanceDistance_over10km	= 7
} e_asn_RelevanceDistance;

/* asn_RelevanceDistance */
typedef long	 asn_RelevanceDistance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_RelevanceDistance;
asn_struct_free_f asn_RelevanceDistance_free;
asn_struct_print_f asn_RelevanceDistance_print;
asn_constr_check_f asn_RelevanceDistance_constraint;
per_type_decoder_f asn_RelevanceDistance_decode_uper;
per_type_encoder_f asn_RelevanceDistance_encode_uper;
per_type_decoder_f asn_RelevanceDistance_decode_aper;
per_type_encoder_f asn_RelevanceDistance_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_RelevanceDistance_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
