/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_HazardousLocation_ObstacleOnTheRoadSubCauseCode_H_
#define	_asn_HazardousLocation_ObstacleOnTheRoadSubCauseCode_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_HazardousLocation_ObstacleOnTheRoadSubCauseCode {
	asn_HazardousLocation_ObstacleOnTheRoadSubCauseCode_unavailable	= 0,
	asn_HazardousLocation_ObstacleOnTheRoadSubCauseCode_shedLoad	= 1,
	asn_HazardousLocation_ObstacleOnTheRoadSubCauseCode_partsOfVehicles	= 2,
	asn_HazardousLocation_ObstacleOnTheRoadSubCauseCode_partsOfTyres	= 3,
	asn_HazardousLocation_ObstacleOnTheRoadSubCauseCode_bigObjects	= 4,
	asn_HazardousLocation_ObstacleOnTheRoadSubCauseCode_fallenTrees	= 5,
	asn_HazardousLocation_ObstacleOnTheRoadSubCauseCode_hubCaps	= 6,
	asn_HazardousLocation_ObstacleOnTheRoadSubCauseCode_waitingVehicles	= 7
} e_asn_HazardousLocation_ObstacleOnTheRoadSubCauseCode;

/* asn_HazardousLocation-ObstacleOnTheRoadSubCauseCode */
typedef long	 asn_HazardousLocation_ObstacleOnTheRoadSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_HazardousLocation_ObstacleOnTheRoadSubCauseCode;
asn_struct_free_f asn_HazardousLocation_ObstacleOnTheRoadSubCauseCode_free;
asn_struct_print_f asn_HazardousLocation_ObstacleOnTheRoadSubCauseCode_print;
asn_constr_check_f asn_HazardousLocation_ObstacleOnTheRoadSubCauseCode_constraint;
per_type_decoder_f asn_HazardousLocation_ObstacleOnTheRoadSubCauseCode_decode_uper;
per_type_encoder_f asn_HazardousLocation_ObstacleOnTheRoadSubCauseCode_encode_uper;
per_type_decoder_f asn_HazardousLocation_ObstacleOnTheRoadSubCauseCode_decode_aper;
per_type_encoder_f asn_HazardousLocation_ObstacleOnTheRoadSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_HazardousLocation_ObstacleOnTheRoadSubCauseCode_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
