/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "/input/CAM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_CoopAwareness_H_
#define	_asn_CoopAwareness_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_thi_prima_coding/asn_GenerationDeltaTime.h"
#include "etsi_its_mcm_thi_prima_coding/asn_CamParameters.h"
#include <etsi_its_mcm_thi_prima_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asn_CoopAwareness */
typedef struct asn_CoopAwareness {
	asn_GenerationDeltaTime_t	 generationDeltaTime;
	asn_CamParameters_t	 camParameters;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asn_CoopAwareness_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_CoopAwareness;
extern asn_SEQUENCE_specifics_t asn_SPC_asn_CoopAwareness_specs_1;
extern asn_TYPE_member_t asn_MBR_asn_CoopAwareness_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _asn_CoopAwareness_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
