/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_SpeedConfidence_H_
#define	_asn_SpeedConfidence_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_SpeedConfidence {
	asn_SpeedConfidence_equalOrWithinOneCentimeterPerSec	= 1,
	asn_SpeedConfidence_equalOrWithinOneMeterPerSec	= 100,
	asn_SpeedConfidence_outOfRange	= 126,
	asn_SpeedConfidence_unavailable	= 127
} e_asn_SpeedConfidence;

/* asn_SpeedConfidence */
typedef long	 asn_SpeedConfidence_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_asn_SpeedConfidence_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_asn_SpeedConfidence;
asn_struct_free_f asn_SpeedConfidence_free;
asn_struct_print_f asn_SpeedConfidence_print;
asn_constr_check_f asn_SpeedConfidence_constraint;
per_type_decoder_f asn_SpeedConfidence_decode_uper;
per_type_encoder_f asn_SpeedConfidence_encode_uper;
per_type_decoder_f asn_SpeedConfidence_decode_aper;
per_type_encoder_f asn_SpeedConfidence_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_SpeedConfidence_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
