/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_Speed_H_
#define	_asn_Speed_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_thi_prima_coding/asn_SpeedValue.h"
#include "etsi_its_mcm_thi_prima_coding/asn_SpeedConfidence.h"
#include <etsi_its_mcm_thi_prima_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asn_Speed */
typedef struct asn_Speed {
	asn_SpeedValue_t	 speedValue;
	asn_SpeedConfidence_t	 speedConfidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asn_Speed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_Speed;
extern asn_SEQUENCE_specifics_t asn_SPC_asn_Speed_specs_1;
extern asn_TYPE_member_t asn_MBR_asn_Speed_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _asn_Speed_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
