/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_CurvatureCalculationMode_H_
#define	_asn_CurvatureCalculationMode_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_CurvatureCalculationMode {
	asn_CurvatureCalculationMode_yawRateUsed	= 0,
	asn_CurvatureCalculationMode_yawRateNotUsed	= 1,
	asn_CurvatureCalculationMode_unavailable	= 2
	/*
	 * Enumeration is extensible
	 */
} e_asn_CurvatureCalculationMode;

/* asn_CurvatureCalculationMode */
typedef long	 asn_CurvatureCalculationMode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_asn_CurvatureCalculationMode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_asn_CurvatureCalculationMode;
extern const asn_INTEGER_specifics_t asn_SPC_asn_CurvatureCalculationMode_specs_1;
asn_struct_free_f asn_CurvatureCalculationMode_free;
asn_struct_print_f asn_CurvatureCalculationMode_print;
asn_constr_check_f asn_CurvatureCalculationMode_constraint;
per_type_decoder_f asn_CurvatureCalculationMode_decode_uper;
per_type_encoder_f asn_CurvatureCalculationMode_encode_uper;
per_type_decoder_f asn_CurvatureCalculationMode_decode_aper;
per_type_encoder_f asn_CurvatureCalculationMode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_CurvatureCalculationMode_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
