/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_StationType_H_
#define	_asn_StationType_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_StationType {
	asn_StationType_unknown	= 0,
	asn_StationType_pedestrian	= 1,
	asn_StationType_cyclist	= 2,
	asn_StationType_moped	= 3,
	asn_StationType_motorcycle	= 4,
	asn_StationType_passengerCar	= 5,
	asn_StationType_bus	= 6,
	asn_StationType_lightTruck	= 7,
	asn_StationType_heavyTruck	= 8,
	asn_StationType_trailer	= 9,
	asn_StationType_specialVehicles	= 10,
	asn_StationType_tram	= 11,
	asn_StationType_roadSideUnit	= 15
} e_asn_StationType;

/* asn_StationType */
typedef long	 asn_StationType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_asn_StationType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_asn_StationType;
asn_struct_free_f asn_StationType_free;
asn_struct_print_f asn_StationType_print;
asn_constr_check_f asn_StationType_constraint;
per_type_decoder_f asn_StationType_decode_uper;
per_type_encoder_f asn_StationType_encode_uper;
per_type_decoder_f asn_StationType_decode_aper;
per_type_encoder_f asn_StationType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_StationType_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
