/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_RelevanceTrafficDirection_H_
#define	_asn_RelevanceTrafficDirection_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_RelevanceTrafficDirection {
	asn_RelevanceTrafficDirection_allTrafficDirections	= 0,
	asn_RelevanceTrafficDirection_upstreamTraffic	= 1,
	asn_RelevanceTrafficDirection_downstreamTraffic	= 2,
	asn_RelevanceTrafficDirection_oppositeTraffic	= 3
} e_asn_RelevanceTrafficDirection;

/* asn_RelevanceTrafficDirection */
typedef long	 asn_RelevanceTrafficDirection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_RelevanceTrafficDirection;
asn_struct_free_f asn_RelevanceTrafficDirection_free;
asn_struct_print_f asn_RelevanceTrafficDirection_print;
asn_constr_check_f asn_RelevanceTrafficDirection_constraint;
per_type_decoder_f asn_RelevanceTrafficDirection_decode_uper;
per_type_encoder_f asn_RelevanceTrafficDirection_encode_uper;
per_type_decoder_f asn_RelevanceTrafficDirection_decode_aper;
per_type_encoder_f asn_RelevanceTrafficDirection_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_RelevanceTrafficDirection_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
