/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_PosConfidenceEllipse_H_
#define	_asn_PosConfidenceEllipse_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_thi_prima_coding/asn_SemiAxisLength.h"
#include "etsi_its_mcm_thi_prima_coding/asn_HeadingValue.h"
#include <etsi_its_mcm_thi_prima_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asn_PosConfidenceEllipse */
typedef struct asn_PosConfidenceEllipse {
	asn_SemiAxisLength_t	 semiMajorConfidence;
	asn_SemiAxisLength_t	 semiMinorConfidence;
	asn_HeadingValue_t	 semiMajorOrientation;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asn_PosConfidenceEllipse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_PosConfidenceEllipse;
extern asn_SEQUENCE_specifics_t asn_SPC_asn_PosConfidenceEllipse_specs_1;
extern asn_TYPE_member_t asn_MBR_asn_PosConfidenceEllipse_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _asn_PosConfidenceEllipse_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
