/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "/input/MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_McmParameters_H_
#define	_asn_McmParameters_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_thi_prima_coding/asn_BasicContainerMCM.h"
#include "etsi_its_mcm_thi_prima_coding/asn_IntentionSharingContainer.h"
#include <etsi_its_mcm_thi_prima_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct asn_ManeuverNegotiationContainer;
struct asn_ManeuverExecutionContainer;
struct asn_ManeuverCoordinationContainer;

/* asn_McmParameters */
typedef struct asn_McmParameters {
	asn_BasicContainerMCM_t	 basicContainerMCM;
	asn_IntentionSharingContainer_t	 intentionSharingContainer;
	struct asn_ManeuverNegotiationContainer	*maneuverNegotiationContainer;	/* OPTIONAL */
	struct asn_ManeuverExecutionContainer	*maneuverExecutionContainer;	/* OPTIONAL */
	struct asn_ManeuverCoordinationContainer	*maneuverCoordinationContainer;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asn_McmParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_McmParameters;
extern asn_SEQUENCE_specifics_t asn_SPC_asn_McmParameters_specs_1;
extern asn_TYPE_member_t asn_MBR_asn_McmParameters_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_mcm_thi_prima_coding/asn_ManeuverNegotiationContainer.h"
#include "etsi_its_mcm_thi_prima_coding/asn_ManeuverExecutionContainer.h"
#include "etsi_its_mcm_thi_prima_coding/asn_ManeuverCoordinationContainer.h"

#endif	/* _asn_McmParameters_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
