/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_SteeringWheelAngle_H_
#define	_asn_SteeringWheelAngle_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_thi_prima_coding/asn_SteeringWheelAngleValue.h"
#include "etsi_its_mcm_thi_prima_coding/asn_SteeringWheelAngleConfidence.h"
#include <etsi_its_mcm_thi_prima_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asn_SteeringWheelAngle */
typedef struct asn_SteeringWheelAngle {
	asn_SteeringWheelAngleValue_t	 steeringWheelAngleValue;
	asn_SteeringWheelAngleConfidence_t	 steeringWheelAngleConfidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asn_SteeringWheelAngle_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_SteeringWheelAngle;
extern asn_SEQUENCE_specifics_t asn_SPC_asn_SteeringWheelAngle_specs_1;
extern asn_TYPE_member_t asn_MBR_asn_SteeringWheelAngle_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _asn_SteeringWheelAngle_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
