/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_PositionOfOccupants_H_
#define	_asn_PositionOfOccupants_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_PositionOfOccupants {
	asn_PositionOfOccupants_row1LeftOccupied	= 0,
	asn_PositionOfOccupants_row1RightOccupied	= 1,
	asn_PositionOfOccupants_row1MidOccupied	= 2,
	asn_PositionOfOccupants_row1NotDetectable	= 3,
	asn_PositionOfOccupants_row1NotPresent	= 4,
	asn_PositionOfOccupants_row2LeftOccupied	= 5,
	asn_PositionOfOccupants_row2RightOccupied	= 6,
	asn_PositionOfOccupants_row2MidOccupied	= 7,
	asn_PositionOfOccupants_row2NotDetectable	= 8,
	asn_PositionOfOccupants_row2NotPresent	= 9,
	asn_PositionOfOccupants_row3LeftOccupied	= 10,
	asn_PositionOfOccupants_row3RightOccupied	= 11,
	asn_PositionOfOccupants_row3MidOccupied	= 12,
	asn_PositionOfOccupants_row3NotDetectable	= 13,
	asn_PositionOfOccupants_row3NotPresent	= 14,
	asn_PositionOfOccupants_row4LeftOccupied	= 15,
	asn_PositionOfOccupants_row4RightOccupied	= 16,
	asn_PositionOfOccupants_row4MidOccupied	= 17,
	asn_PositionOfOccupants_row4NotDetectable	= 18,
	asn_PositionOfOccupants_row4NotPresent	= 19
} e_asn_PositionOfOccupants;

/* asn_PositionOfOccupants */
typedef BIT_STRING_t	 asn_PositionOfOccupants_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_PositionOfOccupants;
asn_struct_free_f asn_PositionOfOccupants_free;
asn_struct_print_f asn_PositionOfOccupants_print;
asn_constr_check_f asn_PositionOfOccupants_constraint;
per_type_decoder_f asn_PositionOfOccupants_decode_uper;
per_type_encoder_f asn_PositionOfOccupants_encode_uper;
per_type_decoder_f asn_PositionOfOccupants_decode_aper;
per_type_encoder_f asn_PositionOfOccupants_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_PositionOfOccupants_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
