/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_VehicleRole_H_
#define	_asn_VehicleRole_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_VehicleRole {
	asn_VehicleRole_default	= 0,
	asn_VehicleRole_publicTransport	= 1,
	asn_VehicleRole_specialTransport	= 2,
	asn_VehicleRole_dangerousGoods	= 3,
	asn_VehicleRole_roadWork	= 4,
	asn_VehicleRole_rescue	= 5,
	asn_VehicleRole_emergency	= 6,
	asn_VehicleRole_safetyCar	= 7,
	asn_VehicleRole_agriculture	= 8,
	asn_VehicleRole_commercial	= 9,
	asn_VehicleRole_military	= 10,
	asn_VehicleRole_roadOperator	= 11,
	asn_VehicleRole_taxi	= 12,
	asn_VehicleRole_reserved1	= 13,
	asn_VehicleRole_reserved2	= 14,
	asn_VehicleRole_reserved3	= 15
} e_asn_VehicleRole;

/* asn_VehicleRole */
typedef long	 asn_VehicleRole_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_asn_VehicleRole_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_asn_VehicleRole;
extern const asn_INTEGER_specifics_t asn_SPC_asn_VehicleRole_specs_1;
asn_struct_free_f asn_VehicleRole_free;
asn_struct_print_f asn_VehicleRole_print;
asn_constr_check_f asn_VehicleRole_constraint;
per_type_decoder_f asn_VehicleRole_decode_uper;
per_type_encoder_f asn_VehicleRole_encode_uper;
per_type_decoder_f asn_VehicleRole_decode_aper;
per_type_encoder_f asn_VehicleRole_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_VehicleRole_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
