/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "/input/MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_IntentionSharingContainer_H_
#define	_asn_IntentionSharingContainer_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_thi_prima_coding/asn_TrajectoryMCM.h"
#include "etsi_its_mcm_thi_prima_coding/asn_Heading.h"
#include "etsi_its_mcm_thi_prima_coding/asn_Speed.h"
#include "etsi_its_mcm_thi_prima_coding/asn_DriveDirection.h"
#include "etsi_its_mcm_thi_prima_coding/asn_VehicleLength.h"
#include "etsi_its_mcm_thi_prima_coding/asn_VehicleWidth.h"
#include "etsi_its_mcm_thi_prima_coding/asn_VehicleAutomationLevel.h"
#include "etsi_its_mcm_thi_prima_coding/asn_LanePosition.h"
#include <etsi_its_mcm_thi_prima_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asn_IntentionSharingContainer */
typedef struct asn_IntentionSharingContainer {
	asn_TrajectoryMCM_t	 plannedTrajectory;
	asn_Heading_t	 heading;
	asn_Speed_t	 speed;
	asn_DriveDirection_t	 driveDirection;
	asn_VehicleLength_t	 vehicleLength;
	asn_VehicleWidth_t	 vehicleWidth;
	asn_VehicleAutomationLevel_t	 vehicleAutomationLevel;
	asn_LanePosition_t	*lanePosition;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asn_IntentionSharingContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_IntentionSharingContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_asn_IntentionSharingContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_asn_IntentionSharingContainer_1[8];

#ifdef __cplusplus
}
#endif

#endif	/* _asn_IntentionSharingContainer_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
