/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_EventHistory_H_
#define	_asn_EventHistory_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_mcm_thi_prima_coding/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct asn_EventPoint;

/* asn_EventHistory */
typedef struct asn_EventHistory {
	A_SEQUENCE_OF(struct asn_EventPoint) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asn_EventHistory_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_EventHistory;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_mcm_thi_prima_coding/asn_EventPoint.h"

#endif	/* _asn_EventHistory_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
