/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "/input/MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_MCM_H_
#define	_asn_MCM_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_thi_prima_coding/asn_ItsPduHeader.h"
#include "etsi_its_mcm_thi_prima_coding/asn_ManeuverCoordinationMessage.h"
#include <etsi_its_mcm_thi_prima_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asn_MCM */
typedef struct asn_MCM {
	asn_ItsPduHeader_t	 header;
	asn_ManeuverCoordinationMessage_t	 mcm;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asn_MCM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_MCM;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_MCM_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
