/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "/input/MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_VehicleAutomationLevel_H_
#define	_asn_VehicleAutomationLevel_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_VehicleAutomationLevel {
	asn_VehicleAutomationLevel_notAvailable	= 0,
	asn_VehicleAutomationLevel_saeLevel1	= 1,
	asn_VehicleAutomationLevel_saeLevel2	= 2,
	asn_VehicleAutomationLevel_saeLevel3	= 3,
	asn_VehicleAutomationLevel_saeLevel4	= 4,
	asn_VehicleAutomationLevel_saeLevel5	= 5
} e_asn_VehicleAutomationLevel;

/* asn_VehicleAutomationLevel */
typedef long	 asn_VehicleAutomationLevel_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_asn_VehicleAutomationLevel_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_asn_VehicleAutomationLevel;
extern const asn_INTEGER_specifics_t asn_SPC_asn_VehicleAutomationLevel_specs_1;
asn_struct_free_f asn_VehicleAutomationLevel_free;
asn_struct_print_f asn_VehicleAutomationLevel_print;
asn_constr_check_f asn_VehicleAutomationLevel_constraint;
per_type_decoder_f asn_VehicleAutomationLevel_decode_uper;
per_type_encoder_f asn_VehicleAutomationLevel_encode_uper;
per_type_decoder_f asn_VehicleAutomationLevel_decode_aper;
per_type_encoder_f asn_VehicleAutomationLevel_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_VehicleAutomationLevel_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
