/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "/input/MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_PriorityManeuver_H_
#define	_asn_PriorityManeuver_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_PriorityManeuver {
	asn_PriorityManeuver_low	= 0,
	asn_PriorityManeuver_medium	= 1,
	asn_PriorityManeuver_high	= 2,
	asn_PriorityManeuver_emergency	= 3
} e_asn_PriorityManeuver;

/* asn_PriorityManeuver */
typedef long	 asn_PriorityManeuver_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_asn_PriorityManeuver_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_asn_PriorityManeuver;
extern const asn_INTEGER_specifics_t asn_SPC_asn_PriorityManeuver_specs_1;
asn_struct_free_f asn_PriorityManeuver_free;
asn_struct_print_f asn_PriorityManeuver_print;
asn_constr_check_f asn_PriorityManeuver_constraint;
per_type_decoder_f asn_PriorityManeuver_decode_uper;
per_type_encoder_f asn_PriorityManeuver_encode_uper;
per_type_decoder_f asn_PriorityManeuver_decode_aper;
per_type_encoder_f asn_PriorityManeuver_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_PriorityManeuver_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
