/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "/input/CAM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_LowFrequencyContainer_H_
#define	_asn_LowFrequencyContainer_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_thi_prima_coding/asn_BasicVehicleContainerLowFrequency.h"
#include <etsi_its_mcm_thi_prima_coding/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_LowFrequencyContainer_PR {
	asn_LowFrequencyContainer_PR_NOTHING,	/* No components present */
	asn_LowFrequencyContainer_PR_basicVehicleContainerLowFrequency
	/* Extensions may appear below */
	
} asn_LowFrequencyContainer_PR;

/* asn_LowFrequencyContainer */
typedef struct asn_LowFrequencyContainer {
	asn_LowFrequencyContainer_PR present;
	union asn_LowFrequencyContainer_u {
		asn_BasicVehicleContainerLowFrequency_t	 basicVehicleContainerLowFrequency;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asn_LowFrequencyContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_LowFrequencyContainer;
extern asn_CHOICE_specifics_t asn_SPC_asn_LowFrequencyContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_asn_LowFrequencyContainer_1[1];
extern asn_per_constraints_t asn_PER_type_asn_LowFrequencyContainer_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_LowFrequencyContainer_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
