/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_VehicleMass_H_
#define	_asn_VehicleMass_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_VehicleMass {
	asn_VehicleMass_hundredKg	= 1,
	asn_VehicleMass_unavailable	= 1024
} e_asn_VehicleMass;

/* asn_VehicleMass */
typedef long	 asn_VehicleMass_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_VehicleMass;
asn_struct_free_f asn_VehicleMass_free;
asn_struct_print_f asn_VehicleMass_print;
asn_constr_check_f asn_VehicleMass_constraint;
per_type_decoder_f asn_VehicleMass_decode_uper;
per_type_encoder_f asn_VehicleMass_encode_uper;
per_type_decoder_f asn_VehicleMass_decode_aper;
per_type_encoder_f asn_VehicleMass_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_VehicleMass_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
