/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_RestrictedTypes_H_
#define	_asn_RestrictedTypes_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_thi_prima_coding/asn_StationType.h"
#include <etsi_its_mcm_thi_prima_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_mcm_thi_prima_coding/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asn_RestrictedTypes */
typedef struct asn_RestrictedTypes {
	A_SEQUENCE_OF(asn_StationType_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asn_RestrictedTypes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_RestrictedTypes;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_RestrictedTypes_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
