/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "/input/MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_BasicContainerMCM_H_
#define	_asn_BasicContainerMCM_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_thi_prima_coding/asn_StationType.h"
#include "etsi_its_mcm_thi_prima_coding/asn_ReferencePosition.h"
#include <etsi_its_mcm_thi_prima_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asn_BasicContainerMCM */
typedef struct asn_BasicContainerMCM {
	asn_StationType_t	 stationType;
	asn_ReferencePosition_t	 referencePosition;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asn_BasicContainerMCM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_BasicContainerMCM;
extern asn_SEQUENCE_specifics_t asn_SPC_asn_BasicContainerMCM_specs_1;
extern asn_TYPE_member_t asn_MBR_asn_BasicContainerMCM_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _asn_BasicContainerMCM_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
