/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_HazardousLocation_SurfaceConditionSubCauseCode_H_
#define	_asn_HazardousLocation_SurfaceConditionSubCauseCode_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_HazardousLocation_SurfaceConditionSubCauseCode {
	asn_HazardousLocation_SurfaceConditionSubCauseCode_unavailable	= 0,
	asn_HazardousLocation_SurfaceConditionSubCauseCode_rockfalls	= 1,
	asn_HazardousLocation_SurfaceConditionSubCauseCode_earthquakeDamage	= 2,
	asn_HazardousLocation_SurfaceConditionSubCauseCode_sewerCollapse	= 3,
	asn_HazardousLocation_SurfaceConditionSubCauseCode_subsidence	= 4,
	asn_HazardousLocation_SurfaceConditionSubCauseCode_snowDrifts	= 5,
	asn_HazardousLocation_SurfaceConditionSubCauseCode_stormDamage	= 6,
	asn_HazardousLocation_SurfaceConditionSubCauseCode_burstPipe	= 7,
	asn_HazardousLocation_SurfaceConditionSubCauseCode_volcanoEruption	= 8,
	asn_HazardousLocation_SurfaceConditionSubCauseCode_fallingIce	= 9
} e_asn_HazardousLocation_SurfaceConditionSubCauseCode;

/* asn_HazardousLocation-SurfaceConditionSubCauseCode */
typedef long	 asn_HazardousLocation_SurfaceConditionSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_HazardousLocation_SurfaceConditionSubCauseCode;
asn_struct_free_f asn_HazardousLocation_SurfaceConditionSubCauseCode_free;
asn_struct_print_f asn_HazardousLocation_SurfaceConditionSubCauseCode_print;
asn_constr_check_f asn_HazardousLocation_SurfaceConditionSubCauseCode_constraint;
per_type_decoder_f asn_HazardousLocation_SurfaceConditionSubCauseCode_decode_uper;
per_type_encoder_f asn_HazardousLocation_SurfaceConditionSubCauseCode_encode_uper;
per_type_decoder_f asn_HazardousLocation_SurfaceConditionSubCauseCode_decode_aper;
per_type_encoder_f asn_HazardousLocation_SurfaceConditionSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_HazardousLocation_SurfaceConditionSubCauseCode_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
