/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "/input/MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_ReasonReject_H_
#define	_asn_ReasonReject_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_ReasonReject {
	asn_ReasonReject_refuseRoadSafetyRisk	= 0,
	asn_ReasonReject_refuseCooperationCostTooHigh	= 1,
	asn_ReasonReject_refuseMisbehaviourDetected	= 2,
	asn_ReasonReject_refuseTrafficRulesNotRespected	= 3,
	asn_ReasonReject_offeredRejected	= 4
} e_asn_ReasonReject;

/* asn_ReasonReject */
typedef long	 asn_ReasonReject_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_asn_ReasonReject_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_asn_ReasonReject;
extern const asn_INTEGER_specifics_t asn_SPC_asn_ReasonReject_specs_1;
asn_struct_free_f asn_ReasonReject_free;
asn_struct_print_f asn_ReasonReject_print;
asn_constr_check_f asn_ReasonReject_constraint;
per_type_decoder_f asn_ReasonReject_decode_uper;
per_type_encoder_f asn_ReasonReject_encode_uper;
per_type_decoder_f asn_ReasonReject_decode_aper;
per_type_encoder_f asn_ReasonReject_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_ReasonReject_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
