/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_TrafficConditionSubCauseCode_H_
#define	_asn_TrafficConditionSubCauseCode_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_TrafficConditionSubCauseCode {
	asn_TrafficConditionSubCauseCode_unavailable	= 0,
	asn_TrafficConditionSubCauseCode_increasedVolumeOfTraffic	= 1,
	asn_TrafficConditionSubCauseCode_trafficJamSlowlyIncreasing	= 2,
	asn_TrafficConditionSubCauseCode_trafficJamIncreasing	= 3,
	asn_TrafficConditionSubCauseCode_trafficJamStronglyIncreasing	= 4,
	asn_TrafficConditionSubCauseCode_trafficStationary	= 5,
	asn_TrafficConditionSubCauseCode_trafficJamSlightlyDecreasing	= 6,
	asn_TrafficConditionSubCauseCode_trafficJamDecreasing	= 7,
	asn_TrafficConditionSubCauseCode_trafficJamStronglyDecreasing	= 8
} e_asn_TrafficConditionSubCauseCode;

/* asn_TrafficConditionSubCauseCode */
typedef long	 asn_TrafficConditionSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_TrafficConditionSubCauseCode;
asn_struct_free_f asn_TrafficConditionSubCauseCode_free;
asn_struct_print_f asn_TrafficConditionSubCauseCode_print;
asn_constr_check_f asn_TrafficConditionSubCauseCode_constraint;
per_type_decoder_f asn_TrafficConditionSubCauseCode_decode_uper;
per_type_encoder_f asn_TrafficConditionSubCauseCode_encode_uper;
per_type_decoder_f asn_TrafficConditionSubCauseCode_decode_aper;
per_type_encoder_f asn_TrafficConditionSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_TrafficConditionSubCauseCode_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
