/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_DangerousSituationSubCauseCode_H_
#define	_asn_DangerousSituationSubCauseCode_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_DangerousSituationSubCauseCode {
	asn_DangerousSituationSubCauseCode_unavailable	= 0,
	asn_DangerousSituationSubCauseCode_emergencyElectronicBrakeEngaged	= 1,
	asn_DangerousSituationSubCauseCode_preCrashSystemEngaged	= 2,
	asn_DangerousSituationSubCauseCode_espEngaged	= 3,
	asn_DangerousSituationSubCauseCode_absEngaged	= 4,
	asn_DangerousSituationSubCauseCode_aebEngaged	= 5,
	asn_DangerousSituationSubCauseCode_brakeWarningEngaged	= 6,
	asn_DangerousSituationSubCauseCode_collisionRiskWarningEngaged	= 7
} e_asn_DangerousSituationSubCauseCode;

/* asn_DangerousSituationSubCauseCode */
typedef long	 asn_DangerousSituationSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_DangerousSituationSubCauseCode;
asn_struct_free_f asn_DangerousSituationSubCauseCode_free;
asn_struct_print_f asn_DangerousSituationSubCauseCode_print;
asn_constr_check_f asn_DangerousSituationSubCauseCode_constraint;
per_type_decoder_f asn_DangerousSituationSubCauseCode_decode_uper;
per_type_encoder_f asn_DangerousSituationSubCauseCode_encode_uper;
per_type_decoder_f asn_DangerousSituationSubCauseCode_decode_aper;
per_type_encoder_f asn_DangerousSituationSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_DangerousSituationSubCauseCode_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
