/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_StationaryVehicleSubCauseCode_H_
#define	_asn_StationaryVehicleSubCauseCode_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_StationaryVehicleSubCauseCode {
	asn_StationaryVehicleSubCauseCode_unavailable	= 0,
	asn_StationaryVehicleSubCauseCode_humanProblem	= 1,
	asn_StationaryVehicleSubCauseCode_vehicleBreakdown	= 2,
	asn_StationaryVehicleSubCauseCode_postCrash	= 3,
	asn_StationaryVehicleSubCauseCode_publicTransportStop	= 4,
	asn_StationaryVehicleSubCauseCode_carryingDangerousGoods	= 5
} e_asn_StationaryVehicleSubCauseCode;

/* asn_StationaryVehicleSubCauseCode */
typedef long	 asn_StationaryVehicleSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_StationaryVehicleSubCauseCode;
asn_struct_free_f asn_StationaryVehicleSubCauseCode_free;
asn_struct_print_f asn_StationaryVehicleSubCauseCode_print;
asn_constr_check_f asn_StationaryVehicleSubCauseCode_constraint;
per_type_decoder_f asn_StationaryVehicleSubCauseCode_decode_uper;
per_type_encoder_f asn_StationaryVehicleSubCauseCode_encode_uper;
per_type_decoder_f asn_StationaryVehicleSubCauseCode_decode_aper;
per_type_encoder_f asn_StationaryVehicleSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_StationaryVehicleSubCauseCode_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
