/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_SlowVehicleSubCauseCode_H_
#define	_asn_SlowVehicleSubCauseCode_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_SlowVehicleSubCauseCode {
	asn_SlowVehicleSubCauseCode_unavailable	= 0,
	asn_SlowVehicleSubCauseCode_maintenanceVehicle	= 1,
	asn_SlowVehicleSubCauseCode_vehiclesSlowingToLookAtAccident	= 2,
	asn_SlowVehicleSubCauseCode_abnormalLoad	= 3,
	asn_SlowVehicleSubCauseCode_abnormalWideLoad	= 4,
	asn_SlowVehicleSubCauseCode_convoy	= 5,
	asn_SlowVehicleSubCauseCode_snowplough	= 6,
	asn_SlowVehicleSubCauseCode_deicing	= 7,
	asn_SlowVehicleSubCauseCode_saltingVehicles	= 8
} e_asn_SlowVehicleSubCauseCode;

/* asn_SlowVehicleSubCauseCode */
typedef long	 asn_SlowVehicleSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_SlowVehicleSubCauseCode;
asn_struct_free_f asn_SlowVehicleSubCauseCode_free;
asn_struct_print_f asn_SlowVehicleSubCauseCode_print;
asn_constr_check_f asn_SlowVehicleSubCauseCode_constraint;
per_type_decoder_f asn_SlowVehicleSubCauseCode_decode_uper;
per_type_encoder_f asn_SlowVehicleSubCauseCode_encode_uper;
per_type_decoder_f asn_SlowVehicleSubCauseCode_decode_aper;
per_type_encoder_f asn_SlowVehicleSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_SlowVehicleSubCauseCode_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
