/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_RoadworksSubCauseCode_H_
#define	_asn_RoadworksSubCauseCode_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_RoadworksSubCauseCode {
	asn_RoadworksSubCauseCode_unavailable	= 0,
	asn_RoadworksSubCauseCode_majorRoadworks	= 1,
	asn_RoadworksSubCauseCode_roadMarkingWork	= 2,
	asn_RoadworksSubCauseCode_slowMovingRoadMaintenance	= 3,
	asn_RoadworksSubCauseCode_shortTermStationaryRoadworks	= 4,
	asn_RoadworksSubCauseCode_streetCleaning	= 5,
	asn_RoadworksSubCauseCode_winterService	= 6
} e_asn_RoadworksSubCauseCode;

/* asn_RoadworksSubCauseCode */
typedef long	 asn_RoadworksSubCauseCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_asn_RoadworksSubCauseCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_asn_RoadworksSubCauseCode;
asn_struct_free_f asn_RoadworksSubCauseCode_free;
asn_struct_print_f asn_RoadworksSubCauseCode_print;
asn_constr_check_f asn_RoadworksSubCauseCode_constraint;
per_type_decoder_f asn_RoadworksSubCauseCode_decode_uper;
per_type_encoder_f asn_RoadworksSubCauseCode_encode_uper;
per_type_decoder_f asn_RoadworksSubCauseCode_decode_aper;
per_type_encoder_f asn_RoadworksSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_RoadworksSubCauseCode_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
