/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_PathHistory_H_
#define	_asn_PathHistory_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_mcm_thi_prima_coding/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct asn_PathPoint;

/* asn_PathHistory */
typedef struct asn_PathHistory {
	A_SEQUENCE_OF(struct asn_PathPoint) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asn_PathHistory_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_PathHistory;
extern asn_SET_OF_specifics_t asn_SPC_asn_PathHistory_specs_1;
extern asn_TYPE_member_t asn_MBR_asn_PathHistory_1[1];
extern asn_per_constraints_t asn_PER_type_asn_PathHistory_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_mcm_thi_prima_coding/asn_PathPoint.h"

#endif	/* _asn_PathHistory_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
