/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_Latitude_H_
#define	_asn_Latitude_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_Latitude {
	asn_Latitude_oneMicrodegreeNorth	= 10,
	asn_Latitude_oneMicrodegreeSouth	= -10,
	asn_Latitude_unavailable	= 900000001
} e_asn_Latitude;

/* asn_Latitude */
typedef long	 asn_Latitude_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_asn_Latitude_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_asn_Latitude;
asn_struct_free_f asn_Latitude_free;
asn_struct_print_f asn_Latitude_print;
asn_constr_check_f asn_Latitude_constraint;
per_type_decoder_f asn_Latitude_decode_uper;
per_type_encoder_f asn_Latitude_encode_uper;
per_type_decoder_f asn_Latitude_decode_aper;
per_type_encoder_f asn_Latitude_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_Latitude_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
