/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_AccelerationControl_H_
#define	_asn_AccelerationControl_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_AccelerationControl {
	asn_AccelerationControl_brakePedalEngaged	= 0,
	asn_AccelerationControl_gasPedalEngaged	= 1,
	asn_AccelerationControl_emergencyBrakeEngaged	= 2,
	asn_AccelerationControl_collisionWarningEngaged	= 3,
	asn_AccelerationControl_accEngaged	= 4,
	asn_AccelerationControl_cruiseControlEngaged	= 5,
	asn_AccelerationControl_speedLimiterEngaged	= 6
} e_asn_AccelerationControl;

/* asn_AccelerationControl */
typedef BIT_STRING_t	 asn_AccelerationControl_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_asn_AccelerationControl_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_asn_AccelerationControl;
asn_struct_free_f asn_AccelerationControl_free;
asn_struct_print_f asn_AccelerationControl_print;
asn_constr_check_f asn_AccelerationControl_constraint;
per_type_decoder_f asn_AccelerationControl_decode_uper;
per_type_encoder_f asn_AccelerationControl_encode_uper;
per_type_decoder_f asn_AccelerationControl_decode_aper;
per_type_encoder_f asn_AccelerationControl_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_AccelerationControl_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
