/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_EventPoint_H_
#define	_asn_EventPoint_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_thi_prima_coding/asn_DeltaReferencePosition.h"
#include "etsi_its_mcm_thi_prima_coding/asn_PathDeltaTime.h"
#include "etsi_its_mcm_thi_prima_coding/asn_InformationQuality.h"
#include <etsi_its_mcm_thi_prima_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asn_EventPoint */
typedef struct asn_EventPoint {
	asn_DeltaReferencePosition_t	 eventPosition;
	asn_PathDeltaTime_t	*eventDeltaTime;	/* OPTIONAL */
	asn_InformationQuality_t	 informationQuality;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asn_EventPoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_EventPoint;
extern asn_SEQUENCE_specifics_t asn_SPC_asn_EventPoint_specs_1;
extern asn_TYPE_member_t asn_MBR_asn_EventPoint_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _asn_EventPoint_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
