/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "/input/CAM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_CamParameters_H_
#define	_asn_CamParameters_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_thi_prima_coding/asn_BasicContainer.h"
#include "etsi_its_mcm_thi_prima_coding/asn_HighFrequencyContainer.h"
#include <etsi_its_mcm_thi_prima_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct asn_LowFrequencyContainer;
struct asn_SpecialVehicleContainer;

/* asn_CamParameters */
typedef struct asn_CamParameters {
	asn_BasicContainer_t	 basicContainer;
	asn_HighFrequencyContainer_t	 highFrequencyContainer;
	struct asn_LowFrequencyContainer	*lowFrequencyContainer;	/* OPTIONAL */
	struct asn_SpecialVehicleContainer	*specialVehicleContainer;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asn_CamParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_CamParameters;
extern asn_SEQUENCE_specifics_t asn_SPC_asn_CamParameters_specs_1;
extern asn_TYPE_member_t asn_MBR_asn_CamParameters_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_mcm_thi_prima_coding/asn_LowFrequencyContainer.h"
#include "etsi_its_mcm_thi_prima_coding/asn_SpecialVehicleContainer.h"

#endif	/* _asn_CamParameters_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
