/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_SignalViolationSubCauseCode_H_
#define	_asn_SignalViolationSubCauseCode_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_SignalViolationSubCauseCode {
	asn_SignalViolationSubCauseCode_unavailable	= 0,
	asn_SignalViolationSubCauseCode_stopSignViolation	= 1,
	asn_SignalViolationSubCauseCode_trafficLightViolation	= 2,
	asn_SignalViolationSubCauseCode_turningRegulationViolation	= 3
} e_asn_SignalViolationSubCauseCode;

/* asn_SignalViolationSubCauseCode */
typedef long	 asn_SignalViolationSubCauseCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_SignalViolationSubCauseCode;
asn_struct_free_f asn_SignalViolationSubCauseCode_free;
asn_struct_print_f asn_SignalViolationSubCauseCode_print;
asn_constr_check_f asn_SignalViolationSubCauseCode_constraint;
per_type_decoder_f asn_SignalViolationSubCauseCode_decode_uper;
per_type_encoder_f asn_SignalViolationSubCauseCode_encode_uper;
per_type_decoder_f asn_SignalViolationSubCauseCode_decode_aper;
per_type_encoder_f asn_SignalViolationSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_SignalViolationSubCauseCode_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
