/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "/input/CAM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_CAM_H_
#define	_asn_CAM_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_thi_prima_coding/asn_ItsPduHeader.h"
#include "etsi_its_mcm_thi_prima_coding/asn_CoopAwareness.h"
#include <etsi_its_mcm_thi_prima_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asn_CAM */
typedef struct asn_CAM {
	asn_ItsPduHeader_t	 header;
	asn_CoopAwareness_t	 cam;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asn_CAM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_CAM;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_CAM_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
