/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_ProtectedCommunicationZone_H_
#define	_asn_ProtectedCommunicationZone_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_thi_prima_coding/asn_ProtectedZoneType.h"
#include "etsi_its_mcm_thi_prima_coding/asn_TimestampIts.h"
#include "etsi_its_mcm_thi_prima_coding/asn_Latitude.h"
#include "etsi_its_mcm_thi_prima_coding/asn_Longitude.h"
#include "etsi_its_mcm_thi_prima_coding/asn_ProtectedZoneRadius.h"
#include "etsi_its_mcm_thi_prima_coding/asn_ProtectedZoneID.h"
#include <etsi_its_mcm_thi_prima_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* asn_ProtectedCommunicationZone */
typedef struct asn_ProtectedCommunicationZone {
	asn_ProtectedZoneType_t	 protectedZoneType;
	asn_TimestampIts_t	*expiryTime;	/* OPTIONAL */
	asn_Latitude_t	 protectedZoneLatitude;
	asn_Longitude_t	 protectedZoneLongitude;
	asn_ProtectedZoneRadius_t	*protectedZoneRadius;	/* OPTIONAL */
	asn_ProtectedZoneID_t	*protectedZoneID;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asn_ProtectedCommunicationZone_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_ProtectedCommunicationZone;
extern asn_SEQUENCE_specifics_t asn_SPC_asn_ProtectedCommunicationZone_specs_1;
extern asn_TYPE_member_t asn_MBR_asn_ProtectedCommunicationZone_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _asn_ProtectedCommunicationZone_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
