/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/input/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_DangerousGoodsBasic_H_
#define	_asn_DangerousGoodsBasic_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_DangerousGoodsBasic {
	asn_DangerousGoodsBasic_explosives1	= 0,
	asn_DangerousGoodsBasic_explosives2	= 1,
	asn_DangerousGoodsBasic_explosives3	= 2,
	asn_DangerousGoodsBasic_explosives4	= 3,
	asn_DangerousGoodsBasic_explosives5	= 4,
	asn_DangerousGoodsBasic_explosives6	= 5,
	asn_DangerousGoodsBasic_flammableGases	= 6,
	asn_DangerousGoodsBasic_nonFlammableGases	= 7,
	asn_DangerousGoodsBasic_toxicGases	= 8,
	asn_DangerousGoodsBasic_flammableLiquids	= 9,
	asn_DangerousGoodsBasic_flammableSolids	= 10,
	asn_DangerousGoodsBasic_substancesLiableToSpontaneousCombustion	= 11,
	asn_DangerousGoodsBasic_substancesEmittingFlammableGasesUponContactWithWater	= 12,
	asn_DangerousGoodsBasic_oxidizingSubstances	= 13,
	asn_DangerousGoodsBasic_organicPeroxides	= 14,
	asn_DangerousGoodsBasic_toxicSubstances	= 15,
	asn_DangerousGoodsBasic_infectiousSubstances	= 16,
	asn_DangerousGoodsBasic_radioactiveMaterial	= 17,
	asn_DangerousGoodsBasic_corrosiveSubstances	= 18,
	asn_DangerousGoodsBasic_miscellaneousDangerousSubstances	= 19
} e_asn_DangerousGoodsBasic;

/* asn_DangerousGoodsBasic */
typedef long	 asn_DangerousGoodsBasic_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_asn_DangerousGoodsBasic_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_asn_DangerousGoodsBasic;
extern const asn_INTEGER_specifics_t asn_SPC_asn_DangerousGoodsBasic_specs_1;
asn_struct_free_f asn_DangerousGoodsBasic_free;
asn_struct_print_f asn_DangerousGoodsBasic_print;
asn_constr_check_f asn_DangerousGoodsBasic_constraint;
per_type_decoder_f asn_DangerousGoodsBasic_decode_uper;
per_type_encoder_f asn_DangerousGoodsBasic_encode_uper;
per_type_decoder_f asn_DangerousGoodsBasic_decode_aper;
per_type_encoder_f asn_DangerousGoodsBasic_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_DangerousGoodsBasic_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
