/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "/input/MCM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_McmCategory_H_
#define	_asn_McmCategory_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_mcm_thi_prima_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum asn_McmCategory {
	asn_McmCategory_request	= 0,
	asn_McmCategory_accept	= 1,
	asn_McmCategory_reject	= 2,
	asn_McmCategory_offer	= 3,
	asn_McmCategory_confirm	= 4,
	asn_McmCategory_execute	= 5,
	asn_McmCategory_cancel	= 6,
	asn_McmCategory_abort	= 7,
	asn_McmCategory_cascadingRequest	= 8,
	asn_McmCategory_cascadingAccept	= 9,
	asn_McmCategory_cascadingReject	= 10,
	asn_McmCategory_cascadingExecute	= 11
} e_asn_McmCategory;

/* asn_McmCategory */
typedef long	 asn_McmCategory_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_asn_McmCategory_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_asn_McmCategory;
extern const asn_INTEGER_specifics_t asn_SPC_asn_McmCategory_specs_1;
asn_struct_free_f asn_McmCategory_free;
asn_struct_print_f asn_McmCategory_print;
asn_constr_check_f asn_McmCategory_constraint;
per_type_decoder_f asn_McmCategory_decode_uper;
per_type_encoder_f asn_McmCategory_encode_uper;
per_type_decoder_f asn_McmCategory_decode_aper;
per_type_encoder_f asn_McmCategory_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _asn_McmCategory_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
