/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "/input/CAM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fprefix=asn_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_asn_EmergencyContainer_H_
#define	_asn_EmergencyContainer_H_


#include <etsi_its_mcm_thi_prima_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_mcm_thi_prima_coding/asn_LightBarSirenInUse.h"
#include "etsi_its_mcm_thi_prima_coding/asn_EmergencyPriority.h"
#include <etsi_its_mcm_thi_prima_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct asn_CauseCode;

/* asn_EmergencyContainer */
typedef struct asn_EmergencyContainer {
	asn_LightBarSirenInUse_t	 lightBarSirenInUse;
	struct asn_CauseCode	*incidentIndication;	/* OPTIONAL */
	asn_EmergencyPriority_t	*emergencyPriority;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} asn_EmergencyContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_asn_EmergencyContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_asn_EmergencyContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_asn_EmergencyContainer_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_mcm_thi_prima_coding/asn_CauseCode.h"

#endif	/* _asn_EmergencyContainer_H_ */
#include <etsi_its_mcm_thi_prima_coding/asn_internal.h>
